# Generated by Django 5.1.2 on 2024-10-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='vibration_level',
            field=models.FloatField(default=0.0),
        ),
    ]
