# Generated by Django 5.1.2 on 2024-10-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0002_machine_machine_name_alter_machine_vibration_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_state',
            field=models.CharField(choices=[('work', 'work'), ('not work', 'not work')], max_length=20, null=True),
        ),
    ]
