# Generated by Django 5.1.2 on 2024-10-18 07:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('machine_type', models.CharField(choices=[('WeldingRobot', 'Welding Robot'), ('StampingPress', 'Stamping Press'), ('PaintingRobot', 'Painting Robot'), ('AGV', 'Automated Guided Vehicle'), ('CNC_Machine', 'CNC Machine'), ('LeakTestMachine', 'Leak Test Machine')], max_length=30)),
                ('vibration_level', models.FloatField()),
                ('temperature', models.IntegerField()),
                ('power_consumation', models.FloatField()),
                ('sensor_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('task_deadline', models.DateTimeField()),
                ('task_type', models.CharField(choices=[('routine', 'routine'), ('urgent', 'urgent'), ('simple', 'simple')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.FloatField()),
                ('maintenance_date', models.DateField(default=datetime.date.today)),
                ('machine_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.machine')),
            ],
        ),
        migrations.CreateModel(
            name='task_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'pending'), ('in progress', 'in progress'), ('done', 'done')], max_length=20)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task')),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Worker', 'Worker')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
