# Generated by Django 5.1.2 on 2024-10-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_maintenance_machine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='sensor_data',
            field=models.TextField(blank=True),
        ),
    ]
